import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
  'en-US': {
    soundAlert: 'Activate the Sound Alert',
    enableAlert: 'Enable alert on (silent mood)',
    message: 'Forms of sending peace and blessings upon Prophet Mohammad',
    volume: 'Alert Volume',
    statistics: 'Statistics',
    week: 'This Week',
    today: 'Today',
    sinceUsingApp: 'Since using the app',
    month: 'This Month',
  },
  en: {
    soundAlert: 'Activate the Sound Alert',
    enableAlert: 'Enable alert on (silent mood)',
    message: 'Forms of sending peace and blessings upon Prophet Mohammad',
    volume: 'Alert Volume',
    statistics: 'Statistics',
    week: 'This Week',
    today: 'Today',
    sinceUsingApp: 'Since using the app',
    month: 'This Month',
  },
  'ar-SA': {
    soundAlert: 'قم بتنشيط تنبيه الصوت',
    enableAlert: 'تفعيل التنبيه على (الحالة الصامتة)',
    message: 'أشكال الصلاة والسلام على النبي محمد',
    volume: 'مستوى صوت التنبيه',
    statistics: 'إحصائيات',
    week: 'هذا الاسبوع',
    today: 'اليوم',
    sinceUsingApp: 'منذ استخدام التطبيق',
    month: 'هذا الشهر',
  },
  'ur-PK': {
    soundAlert: 'صوتی انتباہ کو چالو کریں',
    enableAlert: 'انتباہ کو فعال کریں (خاموش موڈ)',
    message: 'حضرت محمد  پر درود و سلام بھیجنے کی شکلیں۔',
    volume: 'انتباہ والیوم',
    statistics: 'شماریات۔',
    week: 'اس ہفتے',
    today: 'آج',
    sinceUsingApp: 'ایپ استعمال کرنے کے بعد سے۔',
    month: 'اس مہینے',
  },
  sp: {
    soundAlert: 'Activar la alerta sonora',
    enableAlert: 'Habilitar alerta activada (estado de ánimo silencioso)',
    message: 'Formas de enviar paz y bendiciones al Profeta Mahoma',
    volume: 'Volumen de alerta',
    statistics: 'Estadísticas',
    week: 'Esta semana',
    today: 'Hoy dia',
    sinceUsingApp: 'Desde que usó la aplicación',
    month: 'Este mes',
  },
  hi: {
    soundAlert: 'ध्वनि चेतावनी सक्रिय करें',
    enableAlert: 'अलर्ट चालू करें (मौन मूड)',
    message: 'पैगंबर मोहम्मद पर शांति और आशीर्वाद भेजने के तरीके',
    volume: 'अलर्ट वॉल्यूम',
    statistics: 'आंकड़े',
    week: 'इस सप्ताह',
    today: 'आज',
    sinceUsingApp: 'ऐप का उपयोग करने के बाद से',
    month: 'इस महीने',
  },
  it: {
    soundAlert: `Attiva l'avviso sonoro`,
    enableAlert: 'Abilita avviso attivato (umore silenzioso)',
    message: 'Forme per inviare pace e benedizioni al profeta Maometto',
    volume: 'Volume avviso',
    statistics: 'Statistiche',
    week: 'Questa settimana',
    today: 'Oggi',
    sinceUsingApp: ` Da quando uso l'app`,
    month: 'Questo mese',
  },
  pt: {
    soundAlert: 'Ative o Alerta Sonoro',
    enableAlert: 'Ativar alerta (clima silencioso)',
    message: ' Formas de enviar paz e bênçãos ao Profeta Mohammad',
    volume: 'Volume de Alerta',
    statistics: 'Estatisticas',
    week: 'Esta semana',
    today: 'Hoje',
    sinceUsingApp: 'Desde que usei o aplicativo',
    month: 'Este mês',
  },
  id: {
    soundAlert: 'Aktifkan Peringatan Suara',
    enableAlert: 'Aktifkan peringatan aktif (suasana hati senyap)',
    message: ' Bentuk-bentuk shalawat dan salam kepada Nabi Muhammad',
    volume: 'Volume Peringatan',
    statistics: 'Statistik',
    week: 'Minggu ini',
    today: 'Hari ini',
    sinceUsingApp: 'Sejak menggunakan aplikasi',
    month: 'Bulan ini',
  },
  fr: {
    soundAlert: `Activer l'alerte sonore`,
    enableAlert: `Activer l'alerte sur (humeur silencieuse)`,
    message: `Formes d'envoi de la paix et des bénédictions sur le prophète Mohammad`,
    volume: `Volume d'alerte`,
    statistics: 'Statistiques',
    week: 'Cette semaine',
    today: `Aujourd'hui`,
    sinceUsingApp: `Depuis l'utilisation de l'application`,
    month: 'Ce mois-ci',
  },
});
